### ISSUE TITLE
Create mockups for application

### ISSUE THREAD

**Issue by MykhailoSiomachok** [Programming-Engineering-Pmi-33/Schedule#3]
Attach links to screens to comments before closing the issue

**Comment by OlhaDanyliuk** [comment]
[Schedule Page.pdf](https://github.com/Programming-Engineering-Pmi-33/Schedule/files/6121102/Schedule.Page.pdf)
[Login.pdf](https://github.com/Programming-Engineering-Pmi-33/Schedule/files/6121108/Login.pdf)
